name: Run checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        environment: ["py39", "py310", "py311", "py312", "py313", "flake8"]

        include:
          - environment: "py39"
            python: "3.9"
          - environment: "py310"
            python: "3.10"
          - environment: "py311"
            python: "3.11"
          - environment: "py312"
            python: "3.12"
          - environment: "py313"
            python: "3.13"
          - environment: "flake8"
            python: "3.9"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Run tox
      run: |
        tox -e ${{ matrix.environment }}
